const COUNTRY_NAMES = new Map<string, string>([
  ["AF", "Afganistan"],
  ["AL", "Albania"],
  ["DZ", "Aljazair"],
  ["US", "Amerika Serikat"],
  ["AO", "Angola"],
  ["SA", "Arab Saudi"],
  ["AR", "Argentina"],
  ["AM", "Armenia"],
  ["AU", "Australia"],
  ["AT", "Austria"],
  ["AZ", "Azerbaijan"],
  ["BH", "Bahrain"],
  ["BD", "Bangladesh"],
  ["BE", "Belgia"],
  ["BY", "Belarus"],
  ["BO", "Bolivia"],
  ["BA", "Bosnia dan Herzegovina"],
  ["BR", "Brasil"],
  ["GB", "Britania Raya"],
  ["BN", "Brunei Darussalam"],
  ["BG", "Bulgaria"],
  ["KH", "Kamboja"],
  ["CM", "Kamerun"],
  ["CA", "Kanada"],
  ["CN", "Tiongkok"],
  ["CO", "Kolombia"],
  ["KR", "Korea Selatan"],
  ["HR", "Kroasia"],
  ["CZ", "Ceko"],
  ["DK", "Denmark"],
  ["EC", "Ekuador"],
  ["EG", "Mesir"],
  ["AE", "Uni Emirat Arab"],
  ["ES", "Spanyol"],
  ["EE", "Estonia"],
  ["ET", "Etiopia"],
  ["PH", "Filipina"],
  ["FI", "Finlandia"],
  ["FR", "Prancis"],
  ["GH", "Ghana"],
  ["HK", "Hong Kong"],
  ["HU", "Hungaria"],
  ["IN", "India"],
  ["ID", "Indonesia"],
  ["IQ", "Irak"],
  ["IE", "Irlandia"],
  ["IT", "Italia"],
  ["JP", "Jepang"],
  ["DE", "Jerman"],
  ["JO", "Yordania"],
  ["KE", "Kenya"],
  ["KW", "Kuwait"],
  ["LA", "Laos"],
  ["LV", "Latvia"],
  ["LB", "Lebanon"],
  ["LY", "Libya"],
  ["LT", "Lithuania"],
  ["LU", "Luksemburg"],
  ["MY", "Malaysia"],
  ["MX", "Meksiko"],
  ["MA", "Maroko"],
  ["MM", "Myanmar"],
  ["NG", "Nigeria"],
  ["NO", "Norwegia"],
  ["NZ", "Selandia Baru"],
  ["NL", "Belanda"],
  ["OM", "Oman"],
  ["PK", "Pakistan"],
  ["PA", "Panama"],
  ["PG", "Papua Nugini"],
  ["PY", "Paraguay"],
  ["PE", "Peru"],
  ["PL", "Polandia"],
  ["PT", "Portugal"],
  ["QA", "Qatar"],
  ["RO", "Rumania"],
  ["RU", "Rusia"],
  ["SG", "Singapura"],
  ["SK", "Slovakia"],
  ["SI", "Slovenia"],
  ["SL", "Sierra Leone"],
  ["SD", "Sudan"],
  ["SE", "Swedia"],
  ["CH", "Swiss"],
  ["TW", "Taiwan"],
  ["TH", "Thailand"],
  ["TL", "Timor-Leste"],
  ["TR", "Turki"],
  ["UA", "Ukraina"],
  ["UY", "Uruguay"],
  ["UZ", "Uzbekistan"],
  ["VE", "Venezuela"],
  ["VN", "Vietnam"],
  ["YE", "Yaman"],
  ["ZM", "Zambia"],
]);

export function countryName(code: string): string {
  return COUNTRY_NAMES.get(code.toUpperCase()) ?? code;
}