import Link from "next/link";
import { ExternalLink, Search } from "lucide-react";
import type { PublicSourceCatalog } from "../types";

const typeLabels: Record<string, string> = { government: "Pemerintah", statistics_agency: "Statistik", company_report: "Laporan perusahaan", academic: "Akademik", regulation: "Regulasi", market_data: "Data pasar", other: "Lainnya" };
const moduleLabels: Record<string, string> = { education: "Education", industry: "Industry", commodity: "Commodity", career: "Career", intelligence: "Intelligence", economy: "Economy" };

export function SourceCatalog({ catalog, query }: { catalog: PublicSourceCatalog; query: Record<string, string | undefined> }) {
  const pageHref = (page: number) => { const params = new URLSearchParams(); Object.entries(query).forEach(([key, value]) => { if (value && key !== "page") params.set(key, value); }); params.set("page", String(page)); return `/sources?${params}`; };
  return <>
    <form method="get" className="mt-8 grid gap-3 rounded-2xl border border-white/10 bg-[#08172a] p-4 md:grid-cols-[minmax(0,1fr)_repeat(3,minmax(150px,auto))_auto]">
      <label className="relative"><span className="sr-only">Cari sumber</span><Search aria-hidden="true" className="absolute left-3 top-3.5 size-4 text-[#8292a6]"/><input name="q" defaultValue={query.q} maxLength={100} placeholder="Cari publikasi atau instansi" className="h-11 w-full rounded-xl border border-white/10 bg-[#020817] pl-10 pr-3 text-sm outline-none focus:border-brand-cyan"/></label>
      <label><span className="sr-only">Filter instansi</span><select name="publisher" defaultValue={query.publisher ?? ""} className="h-11 w-full rounded-xl border border-white/10 bg-[#020817] px-3 text-sm"><option value="">Semua instansi</option>{catalog.filters.publishers.map((value)=><option key={value}>{value}</option>)}</select></label>
      <label><span className="sr-only">Filter jenis sumber</span><select name="type" defaultValue={query.type ?? ""} className="h-11 w-full rounded-xl border border-white/10 bg-[#020817] px-3 text-sm"><option value="">Semua jenis</option>{catalog.filters.types.map((value)=><option key={value} value={value}>{typeLabels[value] ?? value}</option>)}</select></label>
      <label><span className="sr-only">Filter modul</span><select name="module" defaultValue={query.module ?? ""} className="h-11 w-full rounded-xl border border-white/10 bg-[#020817] px-3 text-sm"><option value="">Semua modul</option>{catalog.filters.modules.map((value)=><option key={value} value={value}>{moduleLabels[value]}</option>)}</select></label>
      <button className="h-11 rounded-xl bg-brand-cyan px-5 text-sm font-bold text-[#020817] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white">Terapkan</button>
    </form>
    <p role="status" className="mt-5 text-sm text-[#9facba]">{catalog.total} sumber publik terverifikasi</p>
    {catalog.items.length ? <div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{catalog.items.map((source)=><article key={source.slug} className="flex min-w-0 flex-col rounded-2xl border border-white/10 bg-[#08172a] p-5"><div className="flex flex-wrap gap-2"><span className="rounded-full bg-brand-cyan/10 px-2.5 py-1 text-xs text-brand-cyan">Sumber terverifikasi</span>{source.modules.map((module)=><span key={module} className="rounded-full border border-white/10 px-2.5 py-1 text-xs text-[#9facba]">{moduleLabels[module]}</span>)}</div><h2 className="mt-4 text-xl">{source.name}</h2><p className="mt-2 text-sm text-[#9facba]">{source.organization} · {typeLabels[source.type]}</p>{source.description ? <p className="mt-3 line-clamp-3 text-sm leading-6 text-[#aebccc]">{source.description}</p> : null}<a href={source.url} target="_blank" rel="noopener noreferrer" className="mt-auto inline-flex min-h-11 items-center gap-2 pt-5 text-sm font-bold text-brand-cyan hover:text-white focus-visible:outline-2 focus-visible:outline-brand-cyan" aria-label={`Buka sumber asli ${source.name} di tab baru`}>Buka sumber asli<ExternalLink aria-hidden="true" className="size-4"/></a></article>)}</div> : <div className="mt-5 rounded-2xl border border-dashed border-white/15 p-10 text-center"><h2 className="text-xl">Sumber tidak ditemukan</h2><p className="mt-2 text-[#9facba]">Coba ubah kata kunci atau filter.</p></div>}
    {catalog.pageCount > 1 ? <nav aria-label="Pagination sumber" className="mt-8 flex items-center justify-center gap-3">{catalog.page > 1 ? <Link className="rounded-full border border-white/15 px-4 py-2" href={pageHref(catalog.page-1)}>Sebelumnya</Link> : null}<span className="text-sm text-[#9facba]">Halaman {catalog.page} dari {catalog.pageCount}</span>{catalog.page < catalog.pageCount ? <Link className="rounded-full border border-white/15 px-4 py-2" href={pageHref(catalog.page+1)}>Berikutnya</Link> : null}</nav> : null}
  </>;
}
